services:

  app:
    build:
      context: ../../.
      dockerfile: .
    container_name: hhp-ecommerce
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hhplus
      SPRING_DATASOURCE_USERNAME: application
      SPRING_DATASOURCE_PASSWORD: application
      SPRING_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - my-app-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G

networks:
  my-app-network:
    external: true
